server {
    listen 80;              # 监听80端口
    server_name localhost;

    # 上传请求体上限 (nginx 默认 1m 会拒绝 2MB 的头像上传, 返回 413)
    client_max_body_size 5m;

    # 静态文件 (禁用 JS 缓存, 方便开发)
    root /usr/share/nginx/html;     # 根目录,当用户访问根域名(http://localhost/)时,Nginx会直接取/usr/share/nginx/html 目录下寻找前端打包好的 index.html 文件,并返回给用户浏览器(实现动静分离)
    index index.html;

    # 正则匹配，拦截所有.js/.css结尾的静态文件请求
    location ~* \.(js|css)$ {
        add_header Cache-Control "no-cache, must-revalidate";
        expires 0;
    }

    # 头像静态文件 (Phase 4.3): 网关把上传的头像写入共享卷, nginx 直接服务
    # alias 把 /avatars/xxx.png 映射到 /data/avatars/xxx.png (尾部斜杠必须对齐)
    location /avatars/ {
        alias /data/avatars/;
        expires 7d;
    }

    # WebSocket 代理到网关
    
    #作用：当浏览器请求 ws://localhost/ws 时，Nginx 会把它转发给后端的 Fastify 网关。
    #Upgrade 和 Connection upgrade 是必须显示配置的Websocket握手配置。因为Nginx默认不支持长连接。
    
    location /ws {
        proxy_pass http://gateway:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400s;      # Nginx 默认 60s 超时, WebSocket 需要长连接, 所以设置为 1 天
    }

    # API 代理到网关
    
    #作用：标准的 HTTP 接口反向代理。把前端发往 /api/xxx 的请求，原封不动地丢给内网 gateway:3000 端口的 Fastify。
    #X-Real-IP：因为穿透了 Nginx，Fastify 默认看到的请求 IP 会变成 Nginx 的内网 IP。加上这行，网关才能通过 req.headers['x-real-ip'] 获取到用户真实的公网 IP（常用于风控或异地登录检测）。
    
    location /api/ {
        proxy_pass http://gateway:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 网关健康检查
    location /health {
        proxy_pass http://gateway:3000;
    }

    # 直连 user-service (绕过网关鉴权, 用于查用户资料)
    # 微服务直连通道(亮点)
    
    #作用：前端发出的特定请求，直接绕过了 Fastify 网关，打到了后端的 C++ 用户微服务上。
    #架构解析：因为底层使用了 bRPC，而 bRPC 框架天然支持 http+pb 或 http+json 协议。这里的 /nova.user.UserService/ 就是 bRPC 标准的服务路由路径。
    #权衡：这种设计可以实现极速查询（比如用来加载公开的用户头像或基础资料），减少了一层网关的转发损耗。但代价是失去了网关的 JWT 鉴权，因此正如你的注释所写，这里只能暴露那些“不需要鉴权也能查看的非敏感信息”。
    
    location /direct/user/ {
        proxy_pass http://user-service:8001/nova.user.UserService/;
        proxy_set_header Host $host;
    }

    
    #作用：定义了底层微服务向网关“反向通信”的路由。
    #架构解析：当 C++ 的 message-service 处理完了一条群聊消息，它需要把消息推给客户端。但客户端的 WebSocket 连在 Fastify 上，所以 C++ 服务会作为客户端，向网关发出一个 HTTP 或 RPC 请求。这里的路径命名规范（包名.服务名）表明，Fastify 网关上可能挂载了一个伪装成 bRPC 服务的接口，专门用来接收底层 C++ 服务的下发任务。
    # PushService (C++ 服务反向推送)
    location /nova.gateway.PushService/ {
        proxy_pass http://gateway:3000;
        proxy_set_header Host $host;
    }
}
