// =============================================================================
// NovaChat — UserService bRPC dispatcher (hand-written for Phase 1)
//
// Uses protoc-generated service descriptor from user.pb.cc for method dispatch.
// bRPC Server calls AddService() → GetDescriptor() → FindMethodByName() → CallMethod()
// =============================================================================

#include "user.brpc.h"
#include <google/protobuf/descriptor.h>

namespace nova {
namespace user {

// Forward: protoc-generated descriptor (defined in user.pb.cc)
// We access it via the static method generated by protoc.
// protoc --cpp_out generates: const ServiceDescriptor* UserService::descriptor()
// which returns a fully-constructed descriptor with all 12 methods.

const google::protobuf::ServiceDescriptor* UserServiceBase::GetDescriptorStatic() {
    // Use protoc-generated descriptor from user.pb.cc
    return nova::user::UserService::descriptor();
}

void UserServiceBase::CallMethod(
    const google::protobuf::MethodDescriptor* method,
    google::protobuf::RpcController* controller,
    const google::protobuf::Message* request,
    google::protobuf::Message* response,
    google::protobuf::Closure* done) {

    const std::string& method_name = method->name();

    // Dispatch by method name (bRPC resolves this from the service descriptor)
    if (method_name == "Register") {
        Register(controller,
                 static_cast<const RegisterReq*>(request),
                 static_cast<RegisterResp*>(response), done);
    } else if (method_name == "Login") {
        Login(controller,
              static_cast<const LoginReq*>(request),
              static_cast<LoginResp*>(response), done);
    } else if (method_name == "RefreshToken") {
        RefreshToken(controller,
                     static_cast<const RefreshTokenReq*>(request),
                     static_cast<RefreshTokenResp*>(response), done);
    } else if (method_name == "Logout") {
        Logout(controller,
               static_cast<const LogoutReq*>(request),
               static_cast<LogoutResp*>(response), done);
    } else if (method_name == "GetUserProfile") {
        GetUserProfile(controller,
                       static_cast<const GetUserProfileReq*>(request),
                       static_cast<GetUserProfileResp*>(response), done);
    } else if (method_name == "GetUsers") {
        GetUsers(controller,
                 static_cast<const GetUsersReq*>(request),
                 static_cast<GetUsersResp*>(response), done);
    } else if (method_name == "UpdateProfile") {
        UpdateProfile(controller,
                      static_cast<const UpdateProfileReq*>(request),
                      static_cast<UpdateProfileResp*>(response), done);
    } else if (method_name == "ChangeUsername") {
        ChangeUsername(controller,
                       static_cast<const ChangeUsernameReq*>(request),
                       static_cast<ChangeUsernameResp*>(response), done);
    } else if (method_name == "CheckUsername") {
        CheckUsername(controller,
                      static_cast<const CheckUsernameReq*>(request),
                      static_cast<CheckUsernameResp*>(response), done);
    } else if (method_name == "ChangePassword") {
        ChangePassword(controller,
                       static_cast<const ChangePasswordReq*>(request),
                       static_cast<ChangePasswordResp*>(response), done);
    } else if (method_name == "SearchUsers") {
        SearchUsers(controller,
                    static_cast<const SearchUsersReq*>(request),
                    static_cast<SearchUsersResp*>(response), done);
    } else if (method_name == "DeleteAccount") {
        DeleteAccount(controller,
                      static_cast<const DeleteAccountReq*>(request),
                      static_cast<DeleteAccountResp*>(response), done);
    } else {
        controller->SetFailed("Unknown method: " + method_name);
        done->Run();
    }
}

const google::protobuf::Message& UserServiceBase::GetRequestPrototype(
    const google::protobuf::MethodDescriptor* method) const {
    return *GetDescriptorStatic()
        ->FindMethodByName(method->name())
        ->input_type()
        ->default_instance();
}

const google::protobuf::Message& UserServiceBase::GetResponsePrototype(
    const google::protobuf::MethodDescriptor* method) const {
    return *GetDescriptorStatic()
        ->FindMethodByName(method->name())
        ->output_type()
        ->default_instance();
}

}  // namespace user
}  // namespace nova
