// =============================================================================
// NovaChat — UserService bRPC Stub (hand-written for Phase 1)
//
// Normally generated by protoc-gen-brpc from user.proto.
// Phase 1 only needs the Service base class; the _Stub is Phase 2+.
// =============================================================================

#pragma once

#include <brpc/server.h>
#include <google/protobuf/service.h>
#include "nova/user/user.pb.h"

namespace nova {
namespace user {

class UserServiceBase : public ::google::protobuf::Service {
public:
    virtual ~UserServiceBase() = default;

    // Auth
    virtual void Register(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::RegisterReq* request,
        ::nova::user::RegisterResp* response,
        ::google::protobuf::Closure* done) = 0;

    virtual void Login(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::LoginReq* request,
        ::nova::user::LoginResp* response,
        ::google::protobuf::Closure* done) = 0;

    virtual void RefreshToken(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::RefreshTokenReq* request,
        ::nova::user::RefreshTokenResp* response,
        ::google::protobuf::Closure* done) = 0;

    virtual void Logout(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::LogoutReq* request,
        ::nova::user::LogoutResp* response,
        ::google::protobuf::Closure* done) = 0;

    // Profile query
    virtual void GetUserProfile(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::GetUserProfileReq* request,
        ::nova::user::GetUserProfileResp* response,
        ::google::protobuf::Closure* done) = 0;

    virtual void GetUsers(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::GetUsersReq* request,
        ::nova::user::GetUsersResp* response,
        ::google::protobuf::Closure* done) = 0;

    // Profile update
    virtual void UpdateProfile(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::UpdateProfileReq* request,
        ::nova::user::UpdateProfileResp* response,
        ::google::protobuf::Closure* done) = 0;

    virtual void ChangeUsername(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::ChangeUsernameReq* request,
        ::nova::user::ChangeUsernameResp* response,
        ::google::protobuf::Closure* done) = 0;

    virtual void CheckUsername(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::CheckUsernameReq* request,
        ::nova::user::CheckUsernameResp* response,
        ::google::protobuf::Closure* done) = 0;

    virtual void ChangePassword(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::ChangePasswordReq* request,
        ::nova::user::ChangePasswordResp* response,
        ::google::protobuf::Closure* done) = 0;

    // Search
    virtual void SearchUsers(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::SearchUsersReq* request,
        ::nova::user::SearchUsersResp* response,
        ::google::protobuf::Closure* done) = 0;

    // Account
    virtual void DeleteAccount(
        ::google::protobuf::RpcController* controller,
        const ::nova::user::DeleteAccountReq* request,
        ::nova::user::DeleteAccountResp* response,
        ::google::protobuf::Closure* done) = 0;

    // ---- google::protobuf::Service interface ----
    const google::protobuf::ServiceDescriptor* GetDescriptor() override {
        return GetDescriptorStatic();
    }

    void CallMethod(
        const google::protobuf::MethodDescriptor* method,
        google::protobuf::RpcController* controller,
        const google::protobuf::Message* request,
        google::protobuf::Message* response,
        google::protobuf::Closure* done) override;

    const google::protobuf::Message& GetRequestPrototype(
        const google::protobuf::MethodDescriptor* method) const override;
    const google::protobuf::Message& GetResponsePrototype(
        const google::protobuf::MethodDescriptor* method) const override;

    // Descriptor
    static const google::protobuf::ServiceDescriptor* GetDescriptorStatic();
};

}  // namespace user
}  // namespace nova
